<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tracker" nsURI="http://fr.rostren.tracker/1.0" nsPrefix="tracker">
  <eClassifiers xsi:type="ecore:EClass" name="Owner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounts" lowerBound="1"
        upperBound="-1" eType="#//Account" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Account" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="isUnique"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckingAccount" eSuperTypes="#//Account">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoockletAccount" eSuperTypes="#//Account">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfers" upperBound="-1"
        eType="#//Transfer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationTitle" lowerBound="1"
        eType="#//OperationTitle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subAmounts" lowerBound="1"
        upperBound="-1" eType="#//Amount" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="#//Origin" eOpposite="#//Origin/operations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="#//Date"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Credit" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Debit" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transfer" abstract="true" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingAccount" eType="#//Account"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingAccount" eType="#//Account"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Incoming" eSuperTypes="#//Transfer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Outgoing" eSuperTypes="#//Transfer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Title" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category" abstract="true" eSuperTypes="#//Title">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationTitles" upperBound="-1"
        eType="#//OperationTitle" eOpposite="#//OperationTitle/categories"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationTitle" eSuperTypes="#//Title">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//Category" eOpposite="#//Category/operationTitles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Amount">
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" lowerBound="1"
        eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wishedDate" eType="#//Date"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationTitleService">
    <eOperations name="addTitle">
      <eParameters name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="deleteTitle">
      <eParameters name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategoryService">
    <eOperations name="addCategory">
      <eParameters name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="deleteCategory">
      <eParameters name="category" eType="#//Category"/>
    </eOperations>
    <eOperations name="addCategoryOperation">
      <eParameters name="operationTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccountService">
    <eOperations name="sumPerCategory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="account" eType="#//Account"/>
      <eParameters name="category" eType="#//Category"/>
      <eParameters name="month" eType="#//Month"/>
      <eParameters name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="averagePerCategory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="account" eType="#//Account"/>
      <eParameters name="category" eType="#//Category"/>
      <eParameters name="month" eType="#//Month"/>
      <eParameters name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationService">
    <eOperations name="sumAmounts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="operation" eType="#//Operation"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategoriesRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="income" lowerBound="1"
        eType="#//IncomeCategory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spending" lowerBound="1"
        eType="#//SpendingCategory" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Origin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//OriginType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="isUnique"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" eOpposite="#//Operation/origin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OriginType">
    <eLiterals name="PDF_FILE"/>
    <eLiterals name="MANUAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OriginsRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="origins" upperBound="-1"
        eType="#//Origin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tracker">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owners" upperBound="-1"
        eType="#//Owner" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originsRepository" lowerBound="1"
        eType="#//OriginsRepository" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categoriesRepository" lowerBound="1"
        eType="#//CategoriesRepository" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationsTitlesRepositories"
        lowerBound="1" eType="#//OperationsTitleRepository" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationsTitleRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationsTitles" upperBound="-1"
        eType="#//OperationTitle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncomeCategory" eSuperTypes="#//Category">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomes" upperBound="-1"
        eType="#//IncomeCategory" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpendingCategory" eSuperTypes="#//Category">
    <eStructuralFeatures xsi:type="ecore:EReference" name="spendings" upperBound="-1"
        eType="#//SpendingCategory" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Date" instanceClassName="java.time.LocalDate"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Month" instanceClassName="java.time.Month"/>
</ecore:EPackage>
