/**
 */
package fr.rostren.tracker.provider.dev;

import org.eclipse.emf.common.notify.Adapter;

import fr.rostren.tracker.provider.TrackerItemProviderAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support
 * Viewers. The adapters generated by this factory convert EMF adapter
 * notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The
 * adapters also support Eclipse property sheets. Note that most of the adapters
 * are shared among multiple instances. <!-- begin-user-doc --> <!--
 * end-user-doc -->
 */
public class TrackerItemProviderAdapterFactoryDev extends
		TrackerItemProviderAdapterFactory {

	/**
	 * This constructs an instance. <!-- begin-user-doc --> <!-- end-user-doc
	 * -->
	 */
	public TrackerItemProviderAdapterFactoryDev() {
		super();
	}

	/**
	 * This creates an adapter for a {@link fr.rostren.tracker.BoockletAccount}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	@Override
	public Adapter createBoockletAccountAdapter() {
		if (boockletAccountItemProvider == null) {
			boockletAccountItemProvider = new BoockletAccountItemProviderDev(
					this);
		}

		return boockletAccountItemProvider;
	}

	/**
	 * This creates an adapter for a {@link fr.rostren.tracker.CheckingAccount}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	@Override
	public Adapter createCheckingAccountAdapter() {
		if (checkingAccountItemProvider == null) {
			checkingAccountItemProvider = new CheckingAccountItemProviderDev(
					this);
		}

		return checkingAccountItemProvider;
	}

	/**
	 * This creates an adapter for a {@link fr.rostren.tracker.CreditOperation}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	@Override
	public Adapter createCreditOperationAdapter() {
		if (creditOperationItemProvider == null) {
			creditOperationItemProvider = new CreditOperationItemProviderDev(
					this);
		}

		return creditOperationItemProvider;
	}

	/**
	 * This creates an adapter for a {@link fr.rostren.tracker.DebitOperation}.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	@Override
	public Adapter createDebitOperationAdapter() {
		if (debitOperationItemProvider == null) {
			debitOperationItemProvider = new DebitOperationItemProviderDev(this);
		}

		return debitOperationItemProvider;
	}

	/**
	 * This creates an adapter for a {@link fr.rostren.tracker.IncomingTransfer}
	 * . <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	@Override
	public Adapter createIncomingTransferAdapter() {
		if (incomingTransferItemProvider == null) {
			incomingTransferItemProvider = new IncomingTransferItemProviderDev(
					this);
		}

		return incomingTransferItemProvider;
	}

	/**
	 * This creates an adapter for a {@link fr.rostren.tracker.OutgoingTransfer}
	 * . <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	@Override
	public Adapter createOutgoingTransferAdapter() {
		if (outgoingTransferItemProvider == null) {
			outgoingTransferItemProvider = new OutgoingTransferItemProviderDev(
					this);
		}

		return outgoingTransferItemProvider;
	}
}
